### Numpy : Linear Algebra Library for Python

Choose one of the following commands:

`conda install numpy`

`pip install numpy`

In [68]:
import numpy as np
np.version.version

'1.15.1'

## Installing

## Numpy Arrays

### Vectors

In [69]:
list = [1,2,3,4]
np_arr = np.array(list)
np_arr

array([1, 2, 3, 4])

### Matrices

In [70]:
# Criando 2D
mat1 = [[1,2,3],[2,4,8],[3,9,27]]
np_arr2 = np.array(mat1)
np_arr2

array([[ 1,  2,  3],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [71]:
list_of_lists = [[1,2,3],[2,4,8],[3,9,27]]
np_mat = np.array(list_of_lists)
np_mat

array([[ 1,  2,  3],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [72]:
np_arr2

array([[ 1,  2,  3],
       [ 2,  4,  8],
       [ 3,  9, 27]])

### Utility functions

#### np.arange

In [73]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(10, 22, 2)

array([10, 12, 14, 16, 18, 20])

In [75]:
np.arange(20, 0, -2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## Special matrices

#### np.eye, np.zeros, np.ones

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.zeros(3)

array([0., 0., 0.])

In [78]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.ones(3)

array([1., 1., 1.])

In [80]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### np.linspace

In [81]:
with_linspace = np.linspace(0, 100, 100)
print('Size:', with_linspace.size)
with_linspace

Size: 100


array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [82]:
with_arange = np.arange(0, 10.1, 0.1)
print('Size:', with_arange.size)
with_arange

Size: 101


array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [83]:
with_linspace = np.linspace(0, 10, 101)
print(with_linspace.size)
with_linspace

101


array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## Generating random data

### Integer

In [84]:
np.random.randint(1, 21)

5

In [85]:
np.random.randint(1, 21, 5)

array([ 3, 16,  6,  4,  6])

In [86]:
np.random.randint(1, 21, 5, dtype='i')

array([ 3,  8, 11, 20, 12], dtype=int32)

In [87]:
np.random.randint(1, 21, 5, dtype='f')

TypeError: Unsupported dtype "float32" for randint

In [88]:
np.random.randint(1, 21, 5).astype("float")

array([ 5., 10., 17., 12.,  3.])

#### Uniform distribution

In [89]:
np.random.rand(3)

array([0.64814708, 0.08444739, 0.48315708])

In [90]:
np.random.rand(2, 3)

array([[0.44058498, 0.48322857, 0.84580062],
       [0.18321655, 0.49592316, 0.2751881 ]])

#### Normal distribution

In [91]:
np.random.randn(2, 2)

array([[-0.59487506,  0.1896957 ],
       [-1.22324685,  3.19230594]])

## Working with np.array

### max(), min(), mean()

In [92]:
l = np.random.randint(1,100,10)
print(l)
print("Max: {} | Min: {} | Average: {}".format(l.max(), l.min(), l.mean()))

[74 56 75 45 12  2 17 51 60 72]
Max: 75 | Min: 2 | Average: 46.4


In [93]:
print("Max value is {} and its index is {}.".format(l.max(), l.argmax()))
print("Min value is {} and its index is {}.".format(l.min(), l.argmin()))

Max value is 75 and its index is 2.
Min value is 2 and its index is 5.


### Dimensions and data types

In [94]:
v = np.random.randint(0, 100, 50)
v

array([24, 99, 35, 50, 28, 45, 73, 40, 89, 40, 28, 14, 97,  4, 86, 99, 89,
       92, 87, 17,  6, 41,  8, 23, 87, 40, 88, 37,  6, 11, 87, 18, 72, 26,
       15, 11, 97, 19, 17, 21, 53, 71, 38, 85, 23, 63, 54, 83, 75, 74])

In [95]:
v.shape

(50,)

In [96]:
v = v.reshape(5, 10)
v

array([[24, 99, 35, 50, 28, 45, 73, 40, 89, 40],
       [28, 14, 97,  4, 86, 99, 89, 92, 87, 17],
       [ 6, 41,  8, 23, 87, 40, 88, 37,  6, 11],
       [87, 18, 72, 26, 15, 11, 97, 19, 17, 21],
       [53, 71, 38, 85, 23, 63, 54, 83, 75, 74]])

In [97]:
v.shape

(5, 10)

In [98]:
v.dtype

dtype('int64')

In [99]:
v = v.astype('f')
v.dtype

dtype('float32')

In [100]:
v

array([[24., 99., 35., 50., 28., 45., 73., 40., 89., 40.],
       [28., 14., 97.,  4., 86., 99., 89., 92., 87., 17.],
       [ 6., 41.,  8., 23., 87., 40., 88., 37.,  6., 11.],
       [87., 18., 72., 26., 15., 11., 97., 19., 17., 21.],
       [53., 71., 38., 85., 23., 63., 54., 83., 75., 74.]], dtype=float32)

### Selection with np.array

#### Selection in vectors

In [101]:
top = [1,2,3,4,5,6]
top[5]

6

In [102]:
p = np.arange(1,21)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [103]:
p[2]

3

In [104]:
p[0:3] 

array([1, 2, 3])

In [105]:
p[:3] 

array([1, 2, 3])

In [106]:
p[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [107]:
p[0:18]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [108]:
p[:-2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

#### Selection in matrices

In [109]:
m = p.reshape(4, 5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [110]:
m[0]

array([1, 2, 3, 4, 5])

In [111]:
m[0, :]

array([1, 2, 3, 4, 5])

In [112]:
m[:,1]

array([ 2,  7, 12, 17])

In [113]:
m[:][1] #Wrong!

array([ 6,  7,  8,  9, 10])

In [114]:
#same result
m[1] 

array([ 6,  7,  8,  9, 10])

In [115]:
#First form
m[0][0]

1

In [116]:
#Alternate form
m[0,0]

1

In [117]:
m[0:2, 0:3]

array([[1, 2, 3],
       [6, 7, 8]])

#### Conditional selection

In [118]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
bool_sel = c > 5

In [120]:
c[bool_sel]

array([6, 7, 8, 9])

In [121]:
c[c < 5]

array([1, 2, 3, 4])

#### np.select()

In [122]:
s = np.arange(1, 10)
cond_list = [s < 3, s > 5]
choice_list = [s, s**2]

In [123]:
choice_list

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])]

In [124]:
cond_list

[array([ True,  True, False, False, False, False, False, False, False]),
 array([False, False, False, False, False,  True,  True,  True,  True])]

In [125]:
np.select(cond_list, choice_list)

array([ 1,  2,  0,  0,  0, 36, 49, 64, 81])

### Broadcast and Copy

In [126]:
x = np.arange(1, 21)
y = x[0:5] 
y

array([1, 2, 3, 4, 5])

In [127]:
y[0:5] = 30
y

array([30, 30, 30, 30, 30])

In [128]:
#Python atribui elementos por referência.
x

array([30, 30, 30, 30, 30,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [129]:
#Para criar uma cópia de valores é necessário usar o método copy()
z = np.arange(1,21)
w = z.copy()[0:5]
w[0:5] = 30
w

array([30, 30, 30, 30, 30])

In [130]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Numpy operations

In [131]:
f = np.arange(0, 5)
g = np.arange(5, 10)
h = f + g
print("{} + {} = {}".format(f, g, h))

[0 1 2 3 4] + [5 6 7 8 9] = [ 5  7  9 11 13]


In [132]:
i = g - f
print("{} - {} = {}".format(g, f, i))

[5 6 7 8 9] - [0 1 2 3 4] = [5 5 5 5 5]


In [133]:
j = f * g
print("{} * {} = {}".format(f, g, j))

[0 1 2 3 4] * [5 6 7 8 9] = [ 0  6 14 24 36]


In [134]:
k = f ** g
print("{} ** {} = {}".format(f, g, k))

[0 1 2 3 4] ** [5 6 7 8 9] = [     0      1    128   6561 262144]


In [135]:
l = f / g
print("{} / {} = {}".format(f, g, l))

[0 1 2 3 4] / [5 6 7 8 9] = [0.         0.16666667 0.28571429 0.375      0.44444444]


In [136]:
print("{} + {} = {}".format(f, 2, f + 2))
print("{} - {} = {}".format(f, 2, f - 2))
print("{} * {} = {}".format(f, 2, f * 2))
print("{} ** {} = {}".format(f, 2, f ** 2))
print("{} / {} = {}".format(f, 2, f / 2))

[0 1 2 3 4] + 2 = [2 3 4 5 6]
[0 1 2 3 4] - 2 = [-2 -1  0  1  2]
[0 1 2 3 4] * 2 = [0 2 4 6 8]
[0 1 2 3 4] ** 2 = [ 0  1  4  9 16]
[0 1 2 3 4] / 2 = [0.  0.5 1.  1.5 2. ]


In [137]:
print("{} / {} = {}".format(f, f, f / f))

[0 1 2 3 4] / [0 1 2 3 4] = [nan  1.  1.  1.  1.]


/Users/Matheus/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [138]:
print("1 / {} = {}".format(f, 1 / f))

1 / [0 1 2 3 4] = [       inf 1.         0.5        0.33333333 0.25      ]


/Users/Matheus/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


## Universal Functions (https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html)

In [139]:
another_matrix = np.arange(1, 13).reshape(3, 4)
print(another_matrix)
maximum = np.max(another_matrix)
minimum = np.min(another_matrix)
average = np.mean(another_matrix)
print("Max = {} | Min = {} | Average = {}".format(maximum, minimum, average))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max = 12 | Min = 1 | Average = 6.5


In [140]:
col_sum = another_matrix.sum(0)
row_sum = another_matrix.sum(1)
print("col_sum:{} | row_sum:{}".format(col_sum, row_sum))

col_sum:[15 18 21 24] | row_sum:[10 26 42]
